import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('103.175.219.57', username='root', password='M4ruw4h3@')
ssh.exec_command('cd /root/news-hybrid && sed -i \'s/printf "\\n" | pecl install redis/pecl install redis/g\' docker/app.Dockerfile')
ssh.exec_command('cd /root/news-hybrid && sed -i \'s/RUN pecl install redis/RUN echo "" | pecl install redis/g\' docker/app.Dockerfile')
stdin, stdout, stderr = ssh.exec_command('cd /root/news-hybrid && ./deploy.sh')
for line in iter(stdout.readline, ''): print(line, end='')
err = stderr.read().decode()
if err: print('STDERR:', err)
ssh.close()
