services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: news_app
    restart: unless-stopped
    ports:
      - "8010:8000"
    volumes:
      - ./app-backend:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - news_net

  worker:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: news_worker
    restart: unless-stopped
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./app-backend:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - news_net

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: news_frontend
    restart: unless-stopped
    ports:
      - "8090:3000"
    depends_on:
      - app
    networks:
      - news_net

  mysql:
    image: mysql:8
    container_name: news_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: news_hybrid
      MYSQL_ROOT_PASSWORD: rootpasswordku
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - news_net

  redis:
    image: redis:alpine
    container_name: news_redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - news_net

  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: news_meili
    restart: unless-stopped
    ports:
      - "7703:7700"
    environment:
      MEILI_MASTER_KEY: super-secret-news-key
    volumes:
      - meili_data:/meili_data
    networks:
      - news_net

volumes:
  mysql_data:
  redis_data:
  meili_data:

networks:
  news_net:
    driver: bridge
