// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/svms-login/Login.tsx": () => import("../components/mockups/svms-login/Login.tsx"),
  "./components/mockups/svms-landing/Landing.tsx": () => import("../components/mockups/svms-landing/Landing.tsx"),
  "./components/mockups/svms-dashboard/Dashboard.tsx": () => import("../components/mockups/svms-dashboard/Dashboard.tsx")
};
